### PR TITLE
implement querySelectorAll

### PR DESCRIPTION
**Pull request by PIC-27**
I simplified the select function, less code more functional and use native function.

### CODE REVIEW

**Comment by wdub** [comment]
First of all, thanks for your contribution. 
I thought on using querySelectorAll but in terms of performance, even getElementsByTagName is faster and that's because QSA is a more complex parser.
[Here](https://github.com/jquery-foundation/standards/issues/4)'s an issue opened by Paul Irish on this subject.
Less code by using QSA or some performance gain by using getElementById / getElementsByClassName ?
What is your opinion regarding the performance aspect ?

**Comment by PIC-27** [comment]
I think the performance impact is negligible for the easy of use. Plus i have made this modification cause your code don't work for this type of selectors ```$('a[href="#'+href+'"]') ```. 
With querySelector we are sure that any selector string will work without making ton of if statement so it balance performance wise.

**Comment by wdub** [comment]
Let's give it a try and see how it goes. Thank you.

**Comment by PIC-27** [comment]
No problem, have a nice day.

**Comment by krokodylowy** [comment]
>Edit : the issue you linked is from 2011, maybe now the performance is not an issue?
Performance problem still exist in  IE9-11 with heavy pages.

**Pull request merged**
